### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by parsamorsal** [parsamorsal/Inverted-Pendulum#1]
Dear Dr. Smith (@smiths),

Please kindly review my problem statement for my Inverted Pendulum project, located [here](https://github.com/parsamorsal/Inverted-Pendulum/blob/master/docs/ProblemStatement/ProblemStatement.pdf).

Thanks.

**Comment by smiths** [comment]
Good start @parsamorsal.  I have the following comments:

- You should clarify what the inputs are to your problem and the outputs - for instance, it is unclear whether you are solving an initial value problem, or if the external perturbation will vary over time
- Are you simulating the pendulum only, or is the control action part of your simulation?
- Please review the writing checklist (in the docs folder).  Specifically, please address the following:
  - do not put generated files (like `.aux` files) under version control
  - hard-wrap text at 80 characters
- Thank you for linking to the file to be reviewed.  You could also include the commit hash for the problem statement.

Once the above comments have been addressed, I'll close this issue, and approve your problem statement.

**Comment by smiths** [comment]
@parsamorsal, have you made some progress on this issue?  It would be great if we could close it so that you can focus on your SRS.

**Comment by parsamorsal** [comment]
Hi Dr. Smith @smiths ,
Thank you for your insightful comments and sorry for the delay. I will have the PS sorted out in a day, to move on to the SRS.

**Comment by parsamorsal** [comment]
Hello Dr. Smith @smiths,
Please kindly review my recent changes in 58402918e6df10d773c5ce4437b4b526f1bc616a.
Thank you.

**Comment by smiths** [comment]
@parsamorsal, I'll approve your problem statement.  I'm still not entirely sure what the inputs and outputs are, but your SRS will make this clear.

There were a few minor LaTeX related problems, so I fixed them in commit 31bb54b.
