### ISSUE TITLE
IM1 Clarification

### ISSUE THREAD

**Issue by andreamclemeno** [parsamorsal/Inverted-Pendulum#15]
Hi @parsamorsal 

This is more of a question but in the description of IM1 on page 8, what do you mean by maximizing the cumulative reward. Does that mean the number of successes?
![image](https://user-images.githubusercontent.com/70977402/97065681-376e4180-157d-11eb-9091-1678cad1c27c.png)

Also, side note: the input and output stated here may help you for your system context!

Andrea

**Comment by parsamorsal** [comment]
It means the sum of all rewards obtained in each step of a single simulation session. 
One unit of reward is given to the DRL agent for each frame of reference in which the pole is not considered fallen.
