### ISSUE TITLE
Instructions within the SRS

### ISSUE THREAD

**Issue by andreamclemeno** [parsamorsal/Inverted-Pendulum#2]
Hi Parsa,

I just started reading your first draft. One quick thing. I think you should take out the pink instructions. It's found in most of the sections. If you want you can comment it out in your .tex file so that you can still see them for future reference!

Thanks,
Andrea

@parsamorsal 
@smiths

**Comment by parsamorsal** [comment]
Hi Andrea,
Sure, I will comment them out. Btw, do you know a way to just turn them off all at once, without having to comment out each of them separately? 
Also, I will have the SRS finalized by Friday at most. 

Thanks.

**Comment by andreamclemeno** [comment]
Hi Parsa! Oh okok! No unfortunately I don't!! I just took mine out instead of commenting it out.

I see what you mean. Sounds good. I will wait until you @ me or I am assigned to a task. Thanks!!
