### ISSUE TITLE
Review VnV Plan

### ISSUE THREAD

**Issue by smiths** [parsamorsal/Inverted-Pendulum#24]
I didn't see an issue created for me to review the VnV Plan, so I've created one.  :smile:

**Comment by smiths** [comment]
Two minor typos corrected in 1b114d5.

**Comment by parsamorsal** [comment]
Hello Dr. Smith,

Sorry, I might have forgotten. Thank you for creating the issue. 
Now that the software is in a more mature state, I have made a couple of new tests that I will add to the VnV today. 

Thanks

**Comment by smiths** [comment]
Feedback on the VnV Plan is given in 8998079.  I will look at the new tests when I review the final documentation.  (I'm glad to see that you have new tests planned, since the VnV plan is currently not comprehensive enough.)

**Comment by smiths** [comment]
The review is completed, so I'll close this issue.
