### ISSUE TITLE
SRS review

### ISSUE THREAD

**Issue by parsamorsal** [parsamorsal/Inverted-Pendulum#3]
Dear Dr. Smith, 

Thank you for your patience and sorry for the delay. 

Please kindly review my [SRS document](https://github.com/parsamorsal/Inverted-Pendulum/blob/master/docs/SRS/SRS.pdf).  

Sincerely,
Parsa

**Comment by parsamorsal** [comment]
Dear @andreamclemeno & @tingyuw,

Please kindly review my SRS document and provide your feedback. I might apply some minor changes as you're reading the initial draft. I will inform you by mentioning the commit hash. 

Sincerely,
Parsa

**Comment by tingyuw** [comment]
Hello @parsamorsal,
I have reviewed your SRS document. I'm sorry if I ask some stupid questions and hope those comments help!

**Comment by parsamorsal** [comment]
Thank you @tingyuw for your thorough review.
They are in fact very helpful and good comments and I was concerned with some of them myself when I was writing the document.
I have started applying your comments. I will provide you with the commit hash as I revise the SRS.

**Comment by parsamorsal** [comment]
Hello @tingyuw, @smiths,

My apologies for the delay. 
In order to fully address the issues you pointed out, I had to run some experiments to understand the limitations of my proposed solution. 
I tried to address most of the issues in dd96397b78284849cd6425070d2ea7a41bf8314a.  The inputs and outputs are now clarified.

Thanks.

**Comment by smiths** [comment]
I pushed an updated `SRS.tex` to correct a spelling typo.

**Comment by smiths** [comment]
Feedback on the SRS is given in commit 7055896.  Please create issues as appropriate.
