### ISSUE TITLE
Degree is not a SI unit

### ISSUE THREAD

**Issue by tingyuw** [parsamorsal/Inverted-Pendulum#4]
Degree is not really a SI unit, although it is accepted in the SI brochure. You can use radian instead. 
symbol/unit/SI : rad/angle/radian
You can see here for more information: https://en.wikipedia.org/wiki/Degree_(angle)

**Comment by parsamorsal** [comment]
dd96397b78284849cd6425070d2ea7a41bf8314a 
I deleted that row since it wasn't necessary.
