### ISSUE TITLE
System context

### ISSUE THREAD

**Issue by tingyuw** [parsamorsal/Inverted-Pendulum#5]
Your system context is too specific and I think it should be in section 4. System Context should be an abstract view of input and output, and it shows the entities your system interact with. It is a data flow diagram, you only need to use circles and rectangles to represent external entities and the system. Your figure 1 is more like a physical system, which should be put in section 4.1.
Also, you need to provide the user and the system responsibilities in this section.
You can follow the description mentioned in the template.
![image](https://user-images.githubusercontent.com/47548045/96544509-b4937100-1274-11eb-9c50-00b1d5cacad8.png)

**Comment by parsamorsal** [comment]
I reformated this section and added a completed description of abstract input and outputs. Also moved the Fig to the next section. dd96397b78284849cd6425070d2ea7a41bf8314a
