### ISSUE TITLE
Functional requirements

### ISSUE THREAD

**Issue by tingyuw** [parsamorsal/Inverted-Pendulum#6]
In the second requirement, you mentioned that the input and output of the system should match the data constraints. But in section 4.2.6, you said there is no strict constraint for inputs on the initial setting. If you have constraints in latter setting or something like that, I think you still need to mention in the data constraint section. If there is no constraint at all, it won't be your system's requirement. 
And I was wondering, in the third requirement, you said your system is expected to obtain a solution in a reasonable amount of time, how do you define a reasonable amount of time? Since it is a requirement of your system, would it be better if you just provide a specific time or time period? In this case, you could verify the requirement easily.

**Comment by smiths** [comment]
Specifying a "reasonable" amount of time is challenging.  How does one justify their choice of a time value?  If the actual time is 1 second longer, does that mean the software failed, even though it is probably fine to take 1 second longer?  For these kind of requirements, I think it is best to look at the underlying requirement, which in this case is usability.  If the performance is poor, then the usability will suffer.  A potential way to state the requirement is to have a survey of users and ask them to rate the usability.  (You can state a requirement this way, even if you don't have specific plans for a usability test in your VnV plan.)

**Comment by parsamorsal** [comment]
Functional and non-functional requirements were a little vague because at that time I didn't have a good estimation of how good the IPP solver would work.
After developing the code a little more and running some tests, I arrived at a more clear definition of the solution with regard to input and outputs.
I have edited that part so it would also be consistent with my VnV plan dd96397
